# Generated by Django 6.0.4 on 2026-05-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_medicaldirectorprofile_receptionistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldirectorprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=50, null=True),
        ),
    ]
