# Generated by Django 6.0.4 on 2026-05-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_medicaldirectorprofile_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceptionistProfile',
        ),
    ]
