# Generated by Django 6.0.4 on 2026-05-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_receptionistprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalDirectorProfile',
        ),
    ]
