# Generated by Django 6.0.4 on 2026-06-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='required_specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
