# Generated by Django 6.0.4 on 2026-05-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='estimated_travel_time',
        ),
        migrations.AddField(
            model_name='referral',
            name='estimated_travel_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='required_specialty',
            field=models.CharField(default='General', help_text='e.g., Cardiology, Orthopedics', max_length=100),
            preserve_default=False,
        ),
    ]
