# Generated by Django 6.0.4 on 2026-05-15 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_consultation'),
        ('referrals', '0002_remove_referral_estimated_travel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.consultation'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='required_specialty',
            field=models.CharField(max_length=100),
        ),
    ]
