# Generated by Django 6.0.4 on 2026-05-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='years_of_experience',
        ),
    ]
