# Generated by Django 6.0.4 on 2026-05-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctorprofile_license_number_and_more'),
    ]

    operations = [
    ]
