# Generated by Django 6.0.4 on 2026-05-16 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_specialty_hospital_specialties_and_more'),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialists', to='hospitals.specialty'),
        ),
    ]
